name: VLESS Alive Checker

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y unzip curl
          pip install requests

      - name: Install Xray
        run: |
          curl -L -o xray.zip https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
          unzip -o xray.zip
          chmod +x xray

      - name: Run checker
        run: python check.py

      - name: Commit result
        run: |
          git add alive_base64.txt
          git commit -m "update alive vless" || echo "no change"
          git push
